name: Publish to NuGet

on:
  create:
    tags:
      - 'v*' # Match any tag starting with 'v'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-restore

      - name: Publish NuGet package
        run: dotnet pack --configuration Release --output ./artifacts --version-suffix ${{ github.ref_name }}

      - name: Publish to NuGet
        uses: nuget/nuget-publish@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: ${{ github.ref_name }}
          nuget-packages-folder: ./artifacts
