name: Publish to NuGet

on:
  push:
    tags:
      - 'v*' # Match any tag starting with 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
        
      - name: Get the version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          VERSION=${VERSION#.}
          echo "::set-output name=VERSION::$VERSION"
          
      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-restore

      - name: Decode certificate and save to file
        run: |
          echo "${{ secrets.CERTIFICATE_BASE64 }}" | base64 -d > ./certificate.pfx

      - name: Sign NuGet package
        run: |
            nuget sign ./artifacts/OchoaLopes.ExprEngine.${{ steps.get_version.outputs.VERSION }}.nupkg \
            -CertificatePath ./certificate.pfx \
            -Timestamper http://timestamp.digicert.com \
            -CertificatePassword ${{ secrets.CERTIFICATE_PASSWORD }}

      - name: Publish NuGet package
        run: dotnet pack --configuration Release --output ./artifacts -p:Version=${{ steps.get_version.outputs.VERSION }}
        
      - name: Publish to NuGet
        run: dotnet nuget push ./artifacts/OchoaLopes.ExprEngine.${{ steps.get_version.outputs.VERSION }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

      - name: Clean up certificate file
        run: rm ./certificate.pfx
