name: Publish to NuGet

env:
  PACKAGE_VERSION: ${{ github.ref }}

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build and test
        run: dotnet build --configuration Release --no-restore

      - name: Build and Publish NuGet package
        run: dotnet pack --configuration Release --output ./artifacts --version-suffix ${{ env.PACKAGE_VERSION }}
        
      - name: Publish to NuGet
        run: dotnet nuget push ./artifacts/OchoaLopes.ExprEngine.${{ env.PACKAGE_VERSION }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      
